name: Run unit tests
on:
    workflow_dispatch:
        inputs:
            trigger_next:
                description: 'Whether to run the subsequent workflows after triggering this one manully.'
                required: false
                default: false
    repository_dispatch:
        types: [main-02-run-unit-tests]

    pull_request:
        branches: ['master', 'development']

jobs:
    unit-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.client_payload.sha }}

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: 16.x

            - name: npm install
              run: npm ci

            - name: Run unit tests
              run: npm run test

            - name: Run e2e tests
              if: success()
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.REPO_GHA_PAT }}
                  repository: wavilikhin/nest-api
                  event-type: main-03-run-e2e-tests
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

            - name: Set final check status
              if: ${{ (github.event_name != 'workflow_dispatch' && failure()) }}
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.REPO_GHA_PAT }}
                  repository: wavilikhin/nest-api
                  event-type: main-05-final-check
                  client-payload: '{"success": false}'
