name: Run e2e tests
on:
    workflow_dispatch:
        inputs:
            trigger_next:
                description: 'Whether to run the subsequent workflows after triggering this one manully.'
                required: false
                default: false
    repository_dispatch:
        types: [main-03-run-e2e-tests]
    push:
    pull_request:
        branches: ['master', 'development']

jobs:
    e2e-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.client_payload.sha }}

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: 16.x

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.6.0
              with:
                  mongodb-version: 4.4.4
            - name: npm install
              run: npm ci
            - name: Run run e2e tests
              run: npm run test:e2e
              env:
                  USE_LOCAL_MONGO_HOST: true

            - name: Publish docker image
              if: success()
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.REPO_GHA_PAT }}
                  repository: wavilikhin/nest-api
                  event-type: main-04-publish-docker-image
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

            - name: Set final check status
              if: ${{ (github.event_name != 'workflow_dispatch' && failure()) }}
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.REPO_GHA_PAT }}
                  repository: wavilikhin/nest-api
                  event-type: main-05-final-check
                  client-payload: '{"success": false}'
