name: Publish docker image
on:
    workflow_dispatch:
        inputs:
            trigger_next:
                description: 'Whether to run the subsequent workflows after triggering this one manully.'
                required: false
                default: false
    repository_dispatch:
        types: [main-04-publish-docker-image]
    push:
    pull_request:
        branches: ['master', 'development']

jobs:
    publish-docker-image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.client_payload.sha }}

            - uses: actions/checkout@master
            - name: Publish to registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/wavilikhin/nest-api/nest-api
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tags: development

            - name: Set final check status
              if: ${{ (github.event_name != 'workflow_dispatch' && failure()) }}
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.REPO_GHA_PAT }}
                  repository: wavilikhin/nest-api
                  event-type: main-05-final-check
                  client-payload: '{"success": false}'
